# Generated by Django 3.0.3 on 2020-02-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='person',
            name='longitude',
        ),
        migrations.AddField(
            model_name='person',
            name='can_move',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='mobility',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Location'),
        ),
    ]
