# Generated by Django 3.0.3 on 2020-02-19 13:12

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200206_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.get_image_path),
        ),
    ]
