# Generated by Django 3.0.3 on 2020-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200306_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mission',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
