# Generated by Django 3.0.3 on 2020-03-06 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200306_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Client'),
        ),
    ]
